### ISSUE TITLE
能否自定义 引用内容的透明度

### ISSUE THREAD

**Issue by luckykong** [v2hot/v2ex.rep#1]
能否给个选项，自主选择是否需要添加 opacity:0.8 的设置？
在我的电脑屏幕上，鼠标没点到引用的回复的时候，0.8的透明度，会让文字看起来有种雾蒙蒙的加粗感，反而牵扯了注意力、降低了对回复的关注程度。

**Comment by PipecraftNet** [comment]
其实这是为了阅读时使注意力集中在当前回复，而不是被引用的回复。想看被引用的回复时，鼠标移上去，就清晰了。
本来 opacity 想弄得更低来着。
下个版本我加上这个设置选项吧。

暂时可以先在 v2ex 设置里的自定义 CSS 里添加下段代码解决。

```css
.reply_content .cell.cited_reply {
    opacity: 1;
}
```

**Comment by luckykong** [comment]
又看了一下，似乎我理解错了。如果是单纯的透明，显示没问题。 有问题的，是“很长的引用内容 的透明化”：引用框里显示不全，有滚动条的时候，才会变模糊。

比如这个图

![显示效果](https://i.imgur.com/jCLpsbG.png)

是帖子 [https://www.v2ex.com/t/962254](https://www.v2ex.com/t/962254) 的37 38楼。
这个对比，很明显，37楼的引用内容，虽然有透明，鼠标移过去会变的更醒目。但是没有鼠标的时候，字体轮廓也是很清晰锐利的。
但是在 38楼，引用了一个很长的回复。这个回复，鼠标没有移过去的时候，边缘很模糊，看着还挺粗的。

当然，如果全部取消透明，是没有这个问题的。

另外，截图似乎看着区别不大，但肉眼看上去，挺明显的。。 不知道是不是跟显示器有瓜。

**Comment by PipecraftNet** [comment]
@luckykong 
你好，新版 1.5.0 已发布。

1. 修改了被引用的回复的透明度的 CSS 规则，现在即便有滚动条，字也不会变模糊了。
2. 添加了透明度设置功能。
<img width="765" alt="Screen Shot 2023-08-15 at 13 02 11" src="https://github.com/v2hot/v2ex.rep/assets/88728670/4fbc5a0c-f951-42a8-98bf-bd175794adb4">
3. 上面回复的自定义 CSS 规则已失效。如需自定义，参考下面代码。

```css
.reply_content .cell.cited_reply::after {
    opacity: 0.1 !important;
}
```
